# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubydora}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Beer"]
  s.date = %q{2011-04-22}
  s.description = %q{Fedora Commons REST API ruby library : REQUIRES FCREPO 3.4+}
  s.email = %q{chris@cbeer.info}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rubydora.rb",
    "lib/rubydora/array_with_callback.rb",
    "lib/rubydora/callbacks.rb",
    "lib/rubydora/datastream.rb",
    "lib/rubydora/digital_object.rb",
    "lib/rubydora/ext.rb",
    "lib/rubydora/ext/model_loader.rb",
    "lib/rubydora/ext/solr.rb",
    "lib/rubydora/extension_parameters.rb",
    "lib/rubydora/models_mixin.rb",
    "lib/rubydora/relationships_mixin.rb",
    "lib/rubydora/repository.rb",
    "lib/rubydora/resource_index.rb",
    "lib/rubydora/rest_api_client.rb",
    "lib/rubydora/rest_api_client/v33.rb",
    "lib/rubydora/soap.rb",
    "rubydora.gemspec",
    "spec/datastream_spec.rb",
    "spec/digital_object_spec.rb",
    "spec/ext_model_loader_spec.rb",
    "spec/ext_solr_spec.rb",
    "spec/extension_parameters_spec.rb",
    "spec/integration_test_spec.rb",
    "spec/repository_spec.rb",
    "spec/resource_index_spec.rb",
    "spec/rest_api_client_spec.rb",
    "spec/soap_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/cbeer/rubydora}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{Fedora Commons REST API ruby library}
  s.test_files = [
    "spec/datastream_spec.rb",
    "spec/digital_object_spec.rb",
    "spec/ext_model_loader_spec.rb",
    "spec/ext_solr_spec.rb",
    "spec/extension_parameters_spec.rb",
    "spec/integration_test_spec.rb",
    "spec/repository_spec.rb",
    "spec/resource_index_spec.rb",
    "spec/rest_api_client_spec.rb",
    "spec/soap_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

